name: DiscordGamersPlugin
main: elektro\DiscordGamers\main
version: 1.5.3
api: 3.9.0
author: ElektroPrinz

commands:
  day:
    description: Ändert die tages zeit.
    usage: "/day"
    permission: dcgame.day
  night:
    description: Ändert die tages zeit
    usage: "/night"
    permission:  dcgame.night
  gmc:
    description: Ändere deinen Spielmodus.
    usage: "/gmc"
    permission: dcgame.gmc
  gms:
    description: Ändere deinen Spielmodus.
    usage: /gms
    permission: dcgame.gms
  gma:
    description: Ändere deine Spielmodus.
    usage: /gma
    permission: dcgame.gma
  gmsp:
    description: Ändere deinen Spielmodus
    usage: "/gmsp"
    permission: dcgame.gmsp
permissions:
  dcgame:
    default: op
    description: Rechte zu allen commands
    children:
      dcgame.day:
        description: Erlaubt den /day command zu benutzen.
        default: op
      dcgame.night:
        description: Erlaubt den /night command zu benutzen.
        default: op
      dcgame.gmc:
        description: Allow using
        default: op
      dcgame.gms:
        description: Allow using
        default: op
      dcgame.gma:
        description: Allow using
        default: op
      dcgame.gmsp:
        description: Erlaubt den /gmsp command zu benutzen.
        default: op
